import Character from './character';
import Bowerman from './bowerman';
import Swordsman from './swordsman';
import Magicial from './magician';
import Undead from './undead';
import Zombie from './zombie';
import Daemon from './daemon';
// const batman = new Daemon('Batmen');
// const dbl = new Magical ('Dambldor');
// const vold = new Zombie ('Voldemort');
// const shriek = new Swordsman('Shriek');
// const lenin = new Undead('Lenin');
// const eyes = new Bowerman('Eyes');
